config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  resources 'homes'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_homes_all, only: [:index]

  def index
  end

  def new
    @home = Home.new
  end

  def create
    @home = Home.new(home_params)
    if @home.save
      render 'index'
    else
      render 'new'
    end
  end

  private

  def home_params
    params.permit(:name, :school, :address, :phone, :department, :favorite, :title, :caption)
  end

  def set_homes_all
    @homes = Home.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<h1>Homes#index</h1>

<%= form_with url: homes_path do |f| %>
  <p>
    <%= f.label :name, "氏名" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :school, "学校名" %><br>
    <%= f.text_field :school %>
  </p>
  <p>
    <%= f.label :address, "メールアドレス" %><br>
    <%= f.email_field :address %>
  </p>
  <p>
    <%= f.label :phone, "電話番号" %><br>
    <%= f.phone_field :phone %>
  </p>
  <p>
    <%= f.label :favorite, "趣味" %><br>
    <%= f.text_field :favorite %>
  </p>
  <p>
    <%= f.label :department, "部門" %><br>
    <%= f.text_field :department %>
  </p>
  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :caption, "見出し" %><br>
    <%= f.text_field :caption %>
  </p>


  <%= f.submit "登録する" %>

<% end %>


<hr>
<table>
  <thead>
  <tr>
    <th>名前</th>
    <th>タイトル</th>
  </tr>
  </thead>

  <% @homes.each do |home| %>
  <tr>
   <td><%= home.name %></td>
   <td><%= home.title %></td>
  </tr>
<% end %>
</table>

app/views/homes/new.html.erb
<p>
  <% @homes.each do |home| %>
    <%= home.name %>
  <% end %>
</p>






<%= form_with url: homes_path do |f| %>
  <p>
    <%= f.label :name, "氏名" %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :school, "学校名" %><br>
    <%= f.text_field :school %>
  </p>
  <p>
    <%= f.label :address, "メールアドレス" %><br>
    <%= f.email_field :address %>
  </p>
  <p>
    <%= f.label :phone, "電話番号" %><br>
    <%= f.phone_field :phone %>
  </p>
  <p>
    <%= f.label :favorite, "趣味" %><br>
    <%= f.text_field :favorite %>
  </p>
  <p>
    <%= f.label :department, "部門" %><br>
    <%= f.text_field :department %>
  </p>
  <p>
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :caption, "見出し" %><br>
    <%= f.text_field :caption %>
  </p>


  <%= f.submit "登録する" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeAppQa</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>